### PR TITLE
Allow installation of PHPUnit 7.0

### PR DESCRIPTION
**Pull request by emodric**
It will be released in two weeks time :)

### CODE REVIEW

**Comment by andrerom** [comment]
will it pass? :P

**Comment by emodric** [comment]
Well, the build is broken here anyhow and I can't test locally :)

**Comment by andrerom** [comment]
Attempting fix in PR #69.

**Comment by emodric** [comment]
I'll rebase as soon as you merge :+1:

**Comment by andrerom** [comment]
@emodric done ;)

**Comment by emodric** [comment]
I rebased the branch, but how do you want to handle testing with PHPUnit 7? Does it need to be allowed in ezplatform repo too?

**Comment by andrerom** [comment]
yes, I think we will need a PR there and test against phpunit 7.0 basically _(once it's out for any merges, but PR's can point to beta/rc in-between)_.

**Comment by MarioBlazek** [comment]
@andrerom would you be kind to tag new release with this PR included ? With PHPUnit 7 here we can upgrade PHPUnit on ezpublish-kernel also.

**Comment by andrerom** [comment]
https://github.com/ezsystems/BehatBundle/releases/tag/v6.5.3

**Comment by MarioBlazek** [comment]
Thank you @andrerom.

**Pull request merged**
