### PR TITLE
public random non existing username

### PR DESCRIPTION
**Pull request by miguelcleverti**
Useful method that should be public

### CODE REVIEW

**Comment by miguelcleverti** [comment]
@pcardiga @andrerom @joaoinacio

**Comment by andrerom** [comment]
+1

**Comment by joaoinacio** [comment]
No longer a dependency from https://github.com/ezsystems/PlatformUIBundle/pull/335 , but +1 anyway

**Comment by miguelcleverti** [comment]
As it is no longer a dependency I closed it

**Pull request closed without merging**
