### PR TITLE
Add Textline fieldtype support for Behat tests

### PR DESCRIPTION
**Pull request by miguelcleverti**
Add Textline fieldtype default values, internal name and validator support in Fields Context. Required to run test related to Textline fields.

### CODE REVIEW

**Comment by miguelcleverti** [comment]
@andrerom @bdunogier @dpobel @joaoinacio @pcardiga

**Comment by andrerom** [comment]
+1, however please rebase on top of master so we can see this is passing.

**Comment by miguelcleverti** [comment]
@andrerom all green and ready!

**Comment by andrerom** [comment]
Thanks @miguelcleverti, please go over the others here as well with @rpmsauron to do the same on others in same situation so we can merge them ;)

**Pull request merged**
