### PR TITLE
Util methods to get field identifier and contentId, minor fixes

### PR DESCRIPTION
**Pull request by joaoinacio**
Ref: https://github.com/ezsystems/PlatformUIBundle/pull/416

### CODE REVIEW

**Comment by andrerom** [comment]
I'm pretty sure ez (cs) robot would have said the spaces within the array blocks is unneeded.

But otherwise +1

**Comment by joaoinacio** [comment]
@andrerom: 
it seems to be the same for the rest of the file, so I went with consistency...  
Not sure if theres an ezcs rule for it tbh, also are there any plans for switching to psr here too?

**Comment by miguelcleverti** [comment]
+1

**Comment by joaoinacio** [comment]
merging since it's pretty safe and required for advancing remaining bdd PRs

**Pull request merged**
