### PR TITLE
Minor fixes in the Sentences and Implementation

### PR DESCRIPTION
**Pull request by miguelcleverti**
Added two minor fixes:
* Added missing sentence "I see field with label" implantation
* Fixed letter casing problem in some sentences

### CODE REVIEW

**Comment by miguelcleverti** [comment]
@andrerom @joaoinacio @bdunogier

**Comment by andrerom** [comment]
+1


Side: @joaoinacio any inout on why the failure is happening? ref `  [Behat\Gherkin\Exception\NodeException]                   
  Table does not have same number of columns in every row.   `

**Comment by miguelcleverti** [comment]
@andrerom I already made a comment about this in another PR. The comments that start on [ line 32 of the user group feature file](https://github.com/ezsystems/BehatBundle/blob/master/Features/user_group.feature#L32) cause this error. Most likely they are being parsed as part of the table and not as comments.

**Comment by andrerom** [comment]
testing: https://github.com/ezsystems/BehatBundle/commit/effdfb3f0dc7f9b476cabbdae755995b8f79e831
https://travis-ci.org/ezsystems/ezsystems/BehatBundle/builds/86381103

**Pull request merged**
