### PR TITLE
PlatformUI BDD support fixes/improvements

### PR DESCRIPTION
**Pull request by miguelcleverti**
Mostly support for the platformUI BDD tests:
* added internal mapping for the fields
* validators and default for the textline field
* languages creating support
* minor fixes/improvements
* sentences improvement

### CODE REVIEW

**Comment by miguelcleverti** [comment]
@joaoinacio @andrerom @bdunogier

**Comment by andrerom** [comment]
+1

**Comment by bdunogier** [comment]
Same remark than on #41: since it is a new context, ditch the trait approach, and create a new context.

**Comment by joaoinacio** [comment]
@bdunogier: 
I haven't been actively following BDD tbh, but I'm not certain if that's possible in the same manner as f.e. PlatformUI contexts.

These ultimately extend EzContext so a ContentContext in PlatformUI can still use sentences from Fields (or auth, or whatever).
If Contexts are split in BehatBundle, the base EzContext would loose most basic sentences, so the I'm not sure how the following could be achieved (without multiple inheritance or some other major refactoring anyway):

`
given a language X exists
and a content type exists with field Y
and a content of this type exists in language X
then ...
`

**Comment by bdunogier** [comment]
Each feature needs to explicitly say which contexts it requires. I'm not sure where this would go wrong :)

**Comment by joaoinacio** [comment]
I think the biggest problem could be state information, if completely different contexts are used.
Right now the same context instance can hold information about entity mappings, authentication, etc.

Also, IIUC do you mean specifying in behat.yml the following, in addition to the actual features?
behat/auth context
behat/user context
behat/content context
behat/field context
behat/fieldtype context
platformui/auth context
...
platformui/field context

**Comment by bdunogier** [comment]
> Also, IIUC do you mean specifying in behat.yml the following, in addition to the actual features?
>
> behat/auth context
> behat/user context
> behat/content context
> behat/field context
> behat/fieldtype context
> ...
> platformui/field context

Yes, precisely. Except that you then have a reason to limit what features involve which context, and to focus the feature on the behaviour we are interested in. I've been using that on the tests I have written so far, and it has really not been an issue.

> I think the biggest problem could be state information, if completely different contexts are used.
> Right now the same context instance can hold information about entity mappings, authentication, etc.

There are ways to use contexts within other contexts. See https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/EzPublishRestBundle/Features/Context/UserContentContext.php#L59-L64. The `UserContent` context uses the public methods from the `RestContext`, that takes care of REST specific things (parsing the response into a value object, sending requests, keeping track of objects, ...).

But at least it is composition, not inheritance scattered around a bunch of traits tied to each other :-)

**Comment by bdunogier** [comment]
I feel that this will conflict with #47, is it not ?

If we have diverged too much, maybe this PR should be closed ?

**Comment by miguelcleverti** [comment]
yes let's close this one, I will after pick the changes and open a new PR.

**Pull request closed without merging**
