### PR TITLE
Basic role operations for usage with platformUI behat tests

### PR DESCRIPTION
**Pull request by miguelcleverti**
Basic operations needed to test RoleUI with behat BDD tests

### CODE REVIEW

**Comment by miguelcleverti** [comment]
@andrerom @bdunogier @pcardiga @joaoinacio

**Comment by andrerom** [comment]
+1

**Comment by miguelcleverti** [comment]
@andrerom the error with travis has already been solved

**Comment by andrerom** [comment]
Ok, are you saying I can merge? :)

**Comment by miguelcleverti** [comment]
@andrerom yes I am :smile:

**Pull request merged**
