### PR TITLE
Changed remaining traits into classes

### PR DESCRIPTION
**Pull request by miguelcleverti**
All the traits have now been updated into classes with the latest improvements. Such as the new ArgumentResolver, RepositoryContext, removed `sudo` method calls,  removed object managers, etc.

Dependent of https://github.com/ezsystems/ezplatform/pull/90.

### CODE REVIEW

**Comment by miguelcleverti** [comment]
ping @joaoinacio @bdunogier @andrerom

**Comment by bdunogier** [comment]
That's a LOT of changes for one PR. I wish things could have been separated a bit (CS would have been an easy one, for instance).

Could you please list the changes a bit more in details in the PR's description ?

**Comment by bdunogier** [comment]
But one global question: what packages actually use behatbundle, and for what ?

**Comment by miguelcleverti** [comment]
@bdunogier I will break this commit into smaller ones. The only thing behatbundle is used for is behat tests, so only the packages that have behat tests use this. I think there are only tests in platformui, in the kernel as the behatbundle itself

**Comment by bdunogier** [comment]
> @bdunogier I will break this commit into smaller ones

I didn't really ask that you do it, given how much work it is :-)

> The only thing behatbundle is used for is behat tests, so only the packages that have behat tests use this

It was quite clear that it was used for behat tests, was it not ? ;)
But why is it separated from other repositories again ?

**Comment by miguelcleverti** [comment]
@bdunogier do you mean moving the behatbundle into into PlatformUI/kernel and delete this repo?
I am not sure why it is separated It was already like this when I got here :) so I assumed this was the way to go. Use the behatbundle as a base for the others. But if you think there might be a better approach let's go for it!

**Comment by bdunogier** [comment]
> do you mean moving the behatbundle into into PlatformUI/kernel and delete this repo

Well, kind of ? :-)
The main point is that having an extra package used by N other packages does add extra complexity. Since this pull-request changes a LOT of the features this bundle offers, maybe we could take the opportunity to simplify things.

**Comment by miguelcleverti** [comment]
Okay! so for now I will do something for PlatformUI to see where that leads us!

**Comment by bdunogier** [comment]
Let's slow down a tiny bit here :-)

**Comment by miguelcleverti** [comment]
@bdunogier so what should we do then?

**Comment by miguelcleverti** [comment]
I was only thinking of making a small change to see how it would turn out

**Comment by bdunogier** [comment]
As agreed, this PR will be closed.

The traits -> classes changed in this PR will be moved to the repository they're actually used in (PlatformUI mostly).

Could you confirm the conclusion (and complete it if necessary, and close the PR if you agree @miguelcleverti ?

**Comment by miguelcleverti** [comment]
I confirm the conclusion :)

**Pull request closed without merging**
