### PR TITLE
Move BasicContent ObjectManager into Context

### PR DESCRIPTION
**Pull request by miguelcleverti**
In order to improve the maintainability and ease of usage, the BehatBundle `ObjectManagers` are to be removed.
Some of the functionalities of the `ObjectManagers` are to be discarded while what really is important and needed is moved into the Context.

### CODE REVIEW

**Comment by miguelcleverti** [comment]
ping @bdunogier @joaoinacio @andrerom

**Comment by bdunogier** [comment]
Before anything else: why are we changing this inside behatbundle if we want to stop using it ?

**Comment by miguelcleverti** [comment]
@bdunogier because we have not yet decided where this should really go. So we might as well make the changes we already discussed and agreed on, and later on we can we can still move this elsewhere. The same type of changes have already been done with [Content Type Context](https://github.com/ezsystems/BehatBundle/blob/master/Context/Object/ContentType.php)

**Comment by bdunogier** [comment]
My problem is that by doing this, we are breaking backward compatibility :(

I'm trying to think of an approach that would be both less complex and straight to the point, but I haven't found it yet.

**Comment by bdunogier** [comment]
We must try to deprecate those elements (phpdoc or `trigger_error`) instead of removing them, to avoid breaks such as https://github.com/ezsystems/PlatformUIBundle/pull/582.

**Comment by miguelcleverti** [comment]
Closed in favor of: https://github.com/ezsystems/ezpublish-kernel/pull/1654

**Pull request closed without merging**
