### PR TITLE
EZP-30597: Add limitation parsers

### PR DESCRIPTION
**Pull request by mnocon**
JIRA: https://jira.ez.no/browse/EZP-30597

This PR adds support to BehatBundle for all existing Limitations mentioned in https://doc.ezplatform.com/en/latest/guide/limitation_reference/
Also added an Object State Context, so that the Limitation can be tested.

Example:
```
    Given Language "Polski" with code "pol-PL" exists
    And Object State Group "Colors" with identifier "colors" exists
      | objectStates |
      | red          |
      | green        |
    And I create a role "complexRole"
    And I add policy "content" "create" to "complexRole" with limitations
      | limitationType      | limitationValue      |
      | Subtree             | /Media,/Media/Images |
      | Content Type        | Article,Folder       |
      | Language            | pol-PL,eng-GB        |
      | Location            | /Media,/Media/Images |
      | Parent Content Type | Folder,Article       |
      | Parent Depth        | 5                    |
      | Parent Owner        | self                 |
      | Parent Group        | self                 |
    And I add policy "content" "read" to "complexRole" with limitations
      | limitationType | limitationValue         |
      | State          | colors:green,colors:red |
      | Owner          | self                    |
      | Group          | self                    |
      | Section        | Media,Standard          |
    And I add policy "user" "login" to "complexRole" with limitations
      | limitationType | limitationValue |
      | Siteaccess     | site,admin      |
    And I add policy "section" "assign" to "complexRole" with limitations
      | limitationType | limitationValue |
      | New Section    | Media,Standard  |
    And I add policy "state" "assign" to "complexRole" with limitations
      | limitationType | limitationValue         |
      | New State      | colors:green,colors:red |
```
Result:
Screenshot 2019-06-05 at 11 59 37

Workflow example:
```
  @admin @workflow
  Scenario: Create a Role and assign policies with limitations to it
    Given I create a role "workflowRole"
    And I add policy "workflow" "Change_stage" to "workflowRole" with limitations
      | limitationType      | limitationValue         |
      | Workflow Transition | article_workflow: done  |
    And I add policy "content" "edit" to "workflowRole" with limitations
      | limitationType      | limitationValue         |
      | Workflow Stage      | folder_workflow: done  |
```
Result:
Screenshot 2019-06-05 at 12 30 30

*Notes:* 
- support for Workflow limitations is added, but they cannot be tested on Travis here (only public packages)
- Behat is not SA-aware when using API, that's why the workflow has to be defined under default section

### CODE REVIEW

**Comment by webhdx** [comment]
One remark after my struggle with Symfony 4 - this package has greedy service definition: 
https://github.com/ezsystems/BehatBundle/blob/master/src/bundle/Resources/config/services.yml#L5

Which is very troublesome for Symfony 4. You should not rely on autowiring because almost nothing from ezpublish-kernel can be autowired. Please make separate service definition for all your Parsers and inject services explicitly. This will make less work for me. Thank you.

**Comment by mnocon** [comment]
@micszo @m-tyrala @katarzynazawada the core part is ready for review, but I still need to address @webhdx remark (will be in separate commit)

**Comment by mnocon** [comment]
@webhdx the greedy definition is gone in https://github.com/ezsystems/BehatBundle/pull/84/commits/4330161d5187838497d3299182a9f05d10786c2d

**Comment by mnocon** [comment]
No reason, I just didn't think of it :D It's clearly better, renamed in https://github.com/ezsystems/BehatBundle/pull/84/commits/a2e69216a1ae468737cca7bf7afaa09a2aa3e59c (also changed YML to YAML)

**Pull request merged**
